const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const DB_KEY='finanzy_db_v1', SESSION_KEY='finanzy_session';
const categories={income:['Salário','Renda extra','Investimentos','Vendas','Outros'],expense:['Moradia','Alimentação','Transporte','Saúde','Educação','Lazer','Assinaturas','Compras','Outros']};
const icons={'Salário':'💼','Renda extra':'✨','Moradia':'⌂','Alimentação':'●','Transporte':'◆','Saúde':'✚','Educação':'▤','Lazer':'★','Assinaturas':'◉','Compras':'▣','Outros':'◇','Investimentos':'↗','Vendas':'$'};
let db,session,currentMonth=new Date().toISOString().slice(0,7),simpleMode='',cloud=null,databaseReady=true;

function seed(){const raw=localStorage.getItem(DB_KEY);if(raw)return JSON.parse(raw);const now=new Date(),d=(day,off=0)=>new Date(now.getFullYear(),now.getMonth()+off,day,12).toISOString().slice(0,10);const data={users:[{id:'admin',name:'Administrador',email:'admin@finanzy.com',password:'admin123',role:'admin',active:true,created:d(1,-2)},{id:'demo',name:'Marina Costa',email:'cliente@finanzy.com',password:'cliente123',role:'client',active:true,created:d(3,-1)}],transactions:[{id:uid(),userId:'demo',description:'Salário',value:5200,type:'income',category:'Salário',date:d(5)},{id:uid(),userId:'demo',description:'Aluguel',value:1450,type:'expense',category:'Moradia',date:d(7)},{id:uid(),userId:'demo',description:'Supermercado',value:487.3,type:'expense',category:'Alimentação',date:d(11)},{id:uid(),userId:'demo',description:'Academia',value:119.9,type:'expense',category:'Saúde',date:d(13)},{id:uid(),userId:'demo',description:'Freelance',value:780,type:'income',category:'Renda extra',date:d(15)}],fixed:[{id:uid(),userId:'demo',name:'Aluguel',value:1450,due:7,category:'Moradia'},{id:uid(),userId:'demo',name:'Internet',value:109.9,due:12,category:'Assinaturas'}],goals:[{id:uid(),userId:'demo',name:'Reserva de emergência',target:12000,current:3600,deadline:d(1,8)}]};localStorage.setItem(DB_KEY,JSON.stringify(data));return data}
function save(){if(!cloud)localStorage.setItem(DB_KEY,JSON.stringify(db))}function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2,7)}
function money(v){return Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}function dateBR(d){return new Date(d+'T12:00:00').toLocaleDateString('pt-BR')}
function user(){return db.users.find(u=>u.id===session)}function mine(key){return db[key].filter(x=>x.userId===session)}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(t._timer);t._timer=setTimeout(()=>t.classList.remove('show'),2400)}

async function init(){bind();fillMonths();try{const c=window.FINANZY_SUPABASE;if(c?.url&&c?.publishableKey&&window.supabase){cloud=window.supabase.createClient(c.url,c.publishableKey);const {data,error}=await cloud.auth.getSession();if(error)throw error;if(data.session){session=data.session.user.id;await loadCloud();if(user()&&user().active)return showApp();await cloud.auth.signOut()}db={users:[],transactions:[],fixed:[],goals:[]};showAuth();await checkDatabase()}else{db=seed();session=localStorage.getItem(SESSION_KEY);if(user()&&user().active)showApp();else showAuth()}}catch(err){console.error(err);db={users:[],transactions:[],fixed:[],goals:[]};showAuth();showSetupAlert();}}
async function checkDatabase(){const {error}=await cloud.from('profiles').select('id').limit(1);databaseReady=!error;if(error)showSetupAlert()}
function showSetupAlert(){databaseReady=false;$('#setupAlert').hidden=false;toast('O banco precisa ser configurado no Supabase.')}
async function loadCloud(){const [profiles,transactions,fixed,goals]=await Promise.all([cloud.from('profiles').select('*'),cloud.from('transactions').select('*'),cloud.from('fixed_expenses').select('*'),cloud.from('goals').select('*')]);const failed=[profiles,transactions,fixed,goals].find(x=>x.error);if(failed)throw failed.error;db={users:profiles.data.map(p=>({id:p.id,name:p.name,email:p.email,role:p.role,active:p.active,created:p.created_at.slice(0,10)})),transactions:transactions.data.map(t=>({...t,userId:t.user_id,value:Number(t.value)})),fixed:fixed.data.map(x=>({id:x.id,userId:x.user_id,name:x.name,value:Number(x.value),due:x.due,category:x.category})),goals:goals.data.map(x=>({id:x.id,userId:x.user_id,name:x.name,target:Number(x.target),current:Number(x.current),deadline:x.deadline}))}}
async function cloudInsert(table,row){const {data,error}=await cloud.from(table).insert(row).select().single();if(error)throw error;return data}
function bind(){
 $('#loginForm').addEventListener('submit',login);$('#registerForm').addEventListener('submit',register);$('#showRegister').onclick=()=>swapAuth(true);$('#showLogin').onclick=()=>swapAuth(false);$('#logoutBtn').onclick=logout;
 $$('[data-toggle-password]').forEach(b=>b.onclick=()=>{const i=$('#'+b.dataset.togglePassword);i.type=i.type==='password'?'text':'password'});
 $$('.nav-item[data-page]').forEach(b=>b.onclick=()=>go(b.dataset.page));$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
 $('#menuBtn').onclick=()=>$('.sidebar').classList.toggle('open');$('#quickAdd').onclick=openTransaction;$$('.add-trigger').forEach(b=>b.onclick=openTransaction);$$('.modal-close').forEach(b=>b.onclick=()=>$('#transactionModal').close());$$('.simple-close').forEach(b=>b.onclick=()=>$('#simpleModal').close());
 $('#transactionForm').onsubmit=addTransaction;$$('[name=txType]').forEach(r=>r.onchange=fillCategories);$('#monthFilter').onchange=e=>{currentMonth=e.target.value;renderAll()};$('#searchInput').oninput=renderTransactions;$('#typeFilter').onchange=renderTransactions;
 $('#addFixedBtn').onclick=()=>openSimple('fixed');$('#addGoalBtn').onclick=()=>openSimple('goal');$('#simpleForm').onsubmit=saveSimple;$('#shareWhatsapp').onclick=shareWhatsApp;$('#printReport').onclick=()=>window.print();$('#themeBtn').onclick=()=>{document.body.classList.toggle('light');localStorage.setItem('finanzy_theme',document.body.classList.contains('light')?'light':'dark')};
 if(localStorage.getItem('finanzy_theme')==='light')document.body.classList.add('light');
}
function swapAuth(reg){$('#loginBox').hidden=reg;$('#registerBox').hidden=!reg}
async function login(e){e.preventDefault();const email=$('#loginEmail').value.trim().toLowerCase(),pass=$('#loginPassword').value;if(cloud){try{const {data,error}=await cloud.auth.signInWithPassword({email,password:pass});if(error)throw error;session=data.user.id;await loadCloud();if(!user()?.active){await cloud.auth.signOut();throw new Error('Esta conta está bloqueada.')}showApp();toast('Bem-vindo à Finanzy!')}catch(err){toast(err.message==='Invalid login credentials'?'E-mail ou senha incorretos.':err.message)}return}const found=db.users.find(u=>u.email===email&&u.password===pass);if(!found)return toast('E-mail ou senha incorretos.');if(!found.active)return toast('Esta conta está bloqueada.');session=found.id;localStorage.setItem(SESSION_KEY,session);showApp();toast('Bem-vindo à Finanzy!')}
async function register(e){e.preventDefault();const email=$('#regEmail').value.trim().toLowerCase(),name=$('#regName').value.trim(),password=$('#regPassword').value;if(cloud){if(!databaseReady)return showSetupAlert();try{const {data,error}=await cloud.auth.signUp({email,password,options:{data:{name}}});if(error)throw error;if(data.session){session=data.user.id;await loadCloud();showApp();toast('Conta criada com sucesso!')}else{swapAuth(false);toast('Confira seu e-mail para confirmar o cadastro.')}}catch(err){toast(err.message)}return}if(db.users.some(u=>u.email===email))return toast('Este e-mail já está cadastrado.');const u={id:uid(),name,email,password,role:'client',active:true,created:new Date().toISOString().slice(0,10)};db.users.push(u);save();session=u.id;localStorage.setItem(SESSION_KEY,session);showApp();toast('Conta criada com sucesso!')}
async function logout(){if(cloud)await cloud.auth.signOut();else localStorage.removeItem(SESSION_KEY);session=null;showAuth()}
function showAuth(){$('#appView').hidden=true;$('#authView').hidden=false;swapAuth(false)}
function showApp(){$('#authView').hidden=true;$('#appView').hidden=false;const u=user();$('#welcomeTitle').textContent=`Olá, ${u.name.split(' ')[0]}!`;$('#userAvatar').textContent=u.name[0].toUpperCase();$('#dateGreeting').textContent=new Date().toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'long'});$$('.admin-only').forEach(x=>x.classList.toggle('hidden',u.role!=='admin'));go(u.role==='admin'?'admin':'dashboard');renderAll()}
function go(name){if(name==='admin'&&user().role!=='admin')name='dashboard';$$('.page').forEach(p=>p.classList.remove('active'));$('#'+name+'Page').classList.add('active');$$('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.page===name));$('.sidebar').classList.remove('open');if(name==='reports')renderReport();if(name==='admin')renderAdmin()}
function fillMonths(){const s=$('#monthFilter'),now=new Date();s.innerHTML='';for(let i=0;i<18;i++){const d=new Date(now.getFullYear(),now.getMonth()-i,1),v=d.toISOString().slice(0,7),o=document.createElement('option');o.value=v;o.textContent=d.toLocaleDateString('pt-BR',{month:'long',year:'numeric'});s.appendChild(o)}s.value=currentMonth}
function monthly(){return mine('transactions').filter(t=>t.date.startsWith(currentMonth))}
function renderAll(){renderDashboard();renderTransactions();renderFixed();renderGoals();renderReport();if(user()?.role==='admin')renderAdmin()}
function totals(list=monthly()){return list.reduce((a,t)=>(a[t.type]+=Number(t.value),a),{income:0,expense:0})}
function renderDashboard(){if(user()?.role==='admin')return;const list=monthly(),t=totals(list),bal=t.income-t.expense,rate=t.income?Math.round(bal/t.income*100):0;$('#incomeValue').textContent=money(t.income);$('#expenseValue').textContent=money(t.expense);$('#balanceValue').textContent=money(bal);$('#savingValue').textContent=rate+'%';$('#incomeCount').textContent=`${list.filter(x=>x.type==='income').length} lançamentos`;$('#expenseCount').textContent=`${list.filter(x=>x.type==='expense').length} lançamentos`;$('#balanceHint').textContent=bal>=0?'Você está no caminho certo':'Atenção: despesas acima da renda';renderBars();renderCategories(list);renderRecent(list)}
function renderBars(){const wrap=$('#barChart'),now=new Date(currentMonth+'-02'),months=[];for(let i=5;i>=0;i--){const d=new Date(now.getFullYear(),now.getMonth()-i,1),key=d.toISOString().slice(0,7),ts=totals(mine('transactions').filter(t=>t.date.startsWith(key)));months.push({label:d.toLocaleDateString('pt-BR',{month:'short'}).replace('.',''),...ts})}const max=Math.max(1,...months.flatMap(x=>[x.income,x.expense]));wrap.innerHTML=months.map(m=>`<div class="bar-group"><div class="bars"><i class="bar in" title="${money(m.income)}" style="height:${m.income/max*100}%"></i><i class="bar out" title="${money(m.expense)}" style="height:${m.expense/max*100}%"></i></div><small>${m.label}</small></div>`).join('')}
function renderCategories(list){const exp=list.filter(x=>x.type==='expense'),sum=exp.reduce((a,x)=>a+Number(x.value),0),map={};exp.forEach(x=>map[x.category]=(map[x.category]||0)+Number(x.value));const rows=Object.entries(map).sort((a,b)=>b[1]-a[1]).slice(0,5);$('#categoryChart').innerHTML=rows.length?rows.map(([c,v])=>`<div class="cat-row"><span>${icons[c]||'◇'} ${esc(c)}</span><div class="progress"><i style="width:${v/sum*100}%"></i></div><b>${Math.round(v/sum*100)}%</b></div>`).join(''):'<div class="empty"><span>◎</span><p>Seus gastos aparecerão aqui.</p></div>'}
function renderRecent(list){const l=[...list].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,5);$('#recentList').innerHTML=l.length?l.map(txRow).join(''):'<div class="empty"><p>Nenhuma movimentação neste mês.</p></div>'}
function txRow(t){return `<div class="transaction-row"><div class="tx-main"><span class="tx-icon">${icons[t.category]||'◇'}</span><div><strong>${esc(t.description)}</strong><small>${esc(t.category)} · ${dateBR(t.date)}</small></div></div><span class="tx-amount ${t.type==='income'?'positive':'negative'}">${t.type==='income'?'+':'−'} ${money(t.value)}</span></div>`}
function renderTransactions(){if(!user()||user().role==='admin')return;let list=[...mine('transactions')].sort((a,b)=>b.date.localeCompare(a.date)),q=$('#searchInput').value.toLowerCase(),type=$('#typeFilter').value;if(q)list=list.filter(x=>(x.description+x.category).toLowerCase().includes(q));if(type!=='all')list=list.filter(x=>x.type===type);$('#transactionTable').innerHTML=list.map(t=>`<tr><td><b>${esc(t.description)}</b></td><td>${icons[t.category]||'◇'} ${esc(t.category)}</td><td>${dateBR(t.date)}</td><td><span class="pill ${t.type}">${t.type==='income'?'Receita':'Despesa'}</span></td><td class="${t.type==='income'?'positive':'negative'}"><b>${money(t.value)}</b></td><td><button class="delete-btn" onclick="removeItem('transactions','${t.id}')">×</button></td></tr>`).join('');$('#emptyTransactions').hidden=!!list.length}
function fillCategories(){const type=$('[name=txType]:checked').value;$('#txCategory').innerHTML=categories[type].map(c=>`<option>${c}</option>`).join('')}
function openTransaction(){$('#transactionForm').reset();$('#txDate').value=new Date().toISOString().slice(0,10);fillCategories();$('#transactionModal').showModal()}
async function addTransaction(e){e.preventDefault();try{let item={id:uid(),userId:session,description:$('#txDescription').value.trim(),value:Number($('#txValue').value),date:$('#txDate').value,type:$('[name=txType]:checked').value,category:$('#txCategory').value};if(cloud){const saved=await cloudInsert('transactions',{user_id:session,description:item.description,value:item.value,date:item.date,type:item.type,category:item.category});item={...saved,userId:saved.user_id,value:Number(saved.value)}}db.transactions.push(item);save();$('#transactionModal').close();currentMonth=$('#txDate').value.slice(0,7);$('#monthFilter').value=currentMonth;renderAll();toast('Lançamento salvo!')}catch(err){toast('Não foi possível salvar: '+err.message)}}
function renderFixed(){if(!user()||user().role==='admin')return;const l=mine('fixed');$('#fixedGrid').innerHTML=l.length?l.map(x=>`<article class="feature-card"><div class="feature-card-head"><span class="tx-icon">${icons[x.category]||'◇'}</span><button class="delete-btn" onclick="removeItem('fixed','${x.id}')">×</button></div><h3>${esc(x.name)}</h3><div class="feature-value">${money(x.value)}</div><p class="muted small">Vencimento todo dia ${x.due} · ${esc(x.category)}</p></article>`).join(''):emptyCard('Nenhum gasto fixo','Cadastre aluguel, internet, assinaturas e outras contas recorrentes.')}
function renderGoals(){if(!user()||user().role==='admin')return;const l=mine('goals');$('#goalsGrid').innerHTML=l.length?l.map(x=>{const p=Math.min(100,Math.round(x.current/x.target*100));return `<article class="feature-card"><div class="feature-card-head"><span class="tx-icon">◎</span><button class="delete-btn" onclick="removeItem('goals','${x.id}')">×</button></div><h3>${esc(x.name)}</h3><div class="feature-value">${money(x.current)} <small class="muted">/ ${money(x.target)}</small></div><div class="goal-progress"><div class="progress"><i style="width:${p}%"></i></div></div><div class="goal-meta"><span>${p}% concluído</span><span>Até ${dateBR(x.deadline)}</span></div><div class="feature-actions"><button class="btn primary" onclick="depositGoal('${x.id}')">＋ Guardar dinheiro</button></div></article>`}).join(''):emptyCard('Nenhuma meta criada','Crie uma meta para sua reserva, viagem ou novo projeto.')}
function emptyCard(title,text){return `<article class="feature-card empty"><span>◎</span><h3>${title}</h3><p>${text}</p></article>`}
function openSimple(mode){simpleMode=mode;$('#simpleForm').reset();if(mode==='fixed'){$('#simpleKicker').textContent='CONTA RECORRENTE';$('#simpleTitle').textContent='Novo gasto fixo';$('#simpleFields').innerHTML=`<label class="wide">Nome<input id="sfName" required placeholder="Ex.: Aluguel"></label><label>Valor mensal<input id="sfValue" type="number" step=".01" min=".01" required></label><label>Dia do vencimento<input id="sfDue" type="number" min="1" max="31" required></label><label class="wide">Categoria<select id="sfCategory">${categories.expense.map(x=>`<option>${x}</option>`).join('')}</select></label>`}else{$('#simpleKicker').textContent='NOVO OBJETIVO';$('#simpleTitle').textContent='Nova meta financeira';$('#simpleFields').innerHTML=`<label class="wide">Nome da meta<input id="sfName" required placeholder="Ex.: Reserva de emergência"></label><label>Valor desejado<input id="sfTarget" type="number" step=".01" min=".01" required></label><label>Valor já guardado<input id="sfCurrent" type="number" step=".01" min="0" value="0" required></label><label class="wide">Prazo<input id="sfDeadline" type="date" required></label>`}$('#simpleModal').showModal()}
async function saveSimple(e){e.preventDefault();try{if(simpleMode==='fixed'){let item={id:uid(),userId:session,name:$('#sfName').value.trim(),value:Number($('#sfValue').value),due:Number($('#sfDue').value),category:$('#sfCategory').value};if(cloud){const x=await cloudInsert('fixed_expenses',{user_id:session,name:item.name,value:item.value,due:item.due,category:item.category});item={...x,userId:x.user_id,value:Number(x.value)}}db.fixed.push(item)}else{let item={id:uid(),userId:session,name:$('#sfName').value.trim(),target:Number($('#sfTarget').value),current:Number($('#sfCurrent').value),deadline:$('#sfDeadline').value};if(cloud){const x=await cloudInsert('goals',{user_id:session,name:item.name,target:item.target,current:item.current,deadline:item.deadline});item={...x,userId:x.user_id,target:Number(x.target),current:Number(x.current)}}db.goals.push(item)}save();$('#simpleModal').close();renderAll();toast('Salvo com sucesso!')}catch(err){toast('Não foi possível salvar: '+err.message)}}
async function removeItem(key,id){if(!confirm('Deseja realmente excluir este item?'))return;try{if(cloud){const table={transactions:'transactions',fixed:'fixed_expenses',goals:'goals'}[key];const {error}=await cloud.from(table).delete().eq('id',id);if(error)throw error}db[key]=db[key].filter(x=>x.id!==id);save();renderAll();toast('Item excluído.')}catch(err){toast('Não foi possível excluir: '+err.message)}}
async function depositGoal(id){const g=db.goals.find(x=>x.id===id),v=prompt(`Quanto deseja adicionar à meta “${g.name}”?`);if(v===null)return;const n=Number(v.replace(',','.'));if(!n||n<0)return toast('Digite um valor válido.');const next=Math.min(g.target,g.current+n);try{if(cloud){const {error}=await cloud.from('goals').update({current:next}).eq('id',id);if(error)throw error}g.current=next;save();renderGoals();toast('Valor adicionado à meta!')}catch(err){toast('Não foi possível atualizar: '+err.message)}}
function renderReport(){if(!user()||user().role==='admin')return;const list=monthly().sort((a,b)=>b.date.localeCompare(a.date)),t=totals(list),bal=t.income-t.expense,rate=t.income?Math.round(bal/t.income*100):0,month=new Date(currentMonth+'-02').toLocaleDateString('pt-BR',{month:'long',year:'numeric'});$('#reportContent').innerHTML=`<div class="report-brand"><div class="logo"><span class="logo-mark">F</span><span>finanzy</span></div><div><b>RELATÓRIO FINANCEIRO</b><p>${month}</p></div></div><h2>Olá, ${esc(user().name.split(' ')[0])}.</h2><p>Este é o resumo das suas finanças no período selecionado.</p><div class="report-summary"><div class="report-box"><span>RECEITAS</span><strong class="positive">${money(t.income)}</strong></div><div class="report-box"><span>DESPESAS</span><strong class="negative">${money(t.expense)}</strong></div><div class="report-box"><span>SALDO FINAL</span><strong>${money(bal)}</strong></div></div><table class="report-table"><thead><tr><th>Descrição</th><th>Data</th><th>Categoria</th><th>Valor</th></tr></thead><tbody>${list.slice(0,12).map(x=>`<tr><td>${esc(x.description)}</td><td>${dateBR(x.date)}</td><td>${esc(x.category)}</td><td>${x.type==='income'?'+':'−'} ${money(x.value)}</td></tr>`).join('')}</tbody></table><div class="report-insight"><b>Diagnóstico Finanzy</b><p>${t.income===0?'Cadastre sua renda para receber uma análise completa.':rate>=20?`Excelente! Você preservou ${rate}% da sua renda neste mês.`:bal>=0?`Você fechou o mês no positivo. Tente elevar sua economia de ${rate}% para pelo menos 20%.`:'Suas despesas ultrapassaram suas receitas. Revise principalmente as maiores categorias de gasto.'}</p></div>`}
function shareWhatsApp(){const t=totals(),bal=t.income-t.expense,month=new Date(currentMonth+'-02').toLocaleDateString('pt-BR',{month:'long',year:'numeric'}),msg=`💰 *Resumo Financeiro Finanzy*\n📅 ${month}\n\n🟢 Receitas: ${money(t.income)}\n🔴 Despesas: ${money(t.expense)}\n💵 Saldo: ${money(bal)}\n\n${bal>=0?'✅ Mês encerrado no positivo!':'⚠️ Despesas acima das receitas.'}\n\n_Gerado com Finanzy_`;window.open('https://wa.me/?text='+encodeURIComponent(msg),'_blank','noopener')}
function renderAdmin(){if(user()?.role!=='admin')return;const clients=db.users.filter(u=>u.role==='client'),tx=db.transactions.length;$('#adminStats').innerHTML=`<article class="stat-card"><span class="stat-icon">♙</span><div><span>Clientes cadastrados</span><strong>${clients.length}</strong><small>${clients.filter(x=>x.active).length} ativos</small></div></article><article class="stat-card"><span class="stat-icon">↔</span><div><span>Total de lançamentos</span><strong>${tx}</strong><small>Em toda a plataforma</small></div></article><article class="stat-card"><span class="stat-icon">◎</span><div><span>Metas criadas</span><strong>${db.goals.length}</strong><small>Pelos clientes</small></div></article><article class="stat-card"><span class="stat-icon">◫</span><div><span>Contas monitoradas</span><strong>${db.fixed.length}</strong><small>Gastos recorrentes</small></div></article>`;$('#usersTable').innerHTML=clients.map(u=>`<tr><td><b>${esc(u.name)}</b></td><td>${esc(u.email)}</td><td>${dateBR(u.created)}</td><td>${db.transactions.filter(t=>t.userId===u.id).length}</td><td><button class="pill ${u.active?'income':'expense'}" onclick="toggleUser('${u.id}')">${u.active?'Ativo':'Bloqueado'}</button></td></tr>`).join('')}
async function toggleUser(id){const u=db.users.find(x=>x.id===id),active=!u.active;try{if(cloud){const {error}=await cloud.from('profiles').update({active}).eq('id',id);if(error)throw error}u.active=active;save();renderAdmin();toast(`Cliente ${u.active?'ativado':'bloqueado'}.`)}catch(err){toast('Não foi possível alterar o cliente: '+err.message)}}
function esc(v){const d=document.createElement('div');d.textContent=v??'';return d.innerHTML}
window.removeItem=removeItem;window.depositGoal=depositGoal;window.toggleUser=toggleUser;document.addEventListener('DOMContentLoaded',init);
